# Site settings
title: REKT
email: contact@gotrekt.com
description: > # this means to ignore newlines until "baseurl:"
  A MOBA where yelling actually does something. Finally.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gotrekt.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
permalink: pretty


# Build settings
markdown: kramdown
